services:
  api:
    depends_on:
      db:
        condition: service_healthy
  db:
    profiles:
      - db
      - local
    image: postgres:17.2
    expose:
      - "5432"
    ports:
      - ${POSTGRES_BIND_IP-[0.0.0.0]}:${POSTGRES_BIND_PORT-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD-DEFAULT_PASSWORD}
      POSTGRES_C_PASSWORD: ${POSTGRES_USER_PASSWORD:-DEFAULT_PASSWORD}
      POSTGRES_HF_PASSWORD: ${POSTGRES_HANGFIRE_USER_PASSWORD:-DEFAULT_PASSWORD}
    volumes:
      - ./Volumes/PostgreSQL/data:/var/lib/postgresql/data
      - ./Volumes/PostgreSQL/postgres-init-files:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d crypter -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
