#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
   CREATE USER cryptuser WITH PASSWORD 'CHANGE_ME';
   CREATE DATABASE crypter;
   REVOKE ALL PRIVILEGES ON DATABASE postgres FROM cryptuser;
   REVOKE ALL PRIVILEGES ON SCHEMA public FROM cryptuser;
   REVOKE CREATE ON SCHEMA public FROM PUBLIC;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "crypter" <<-EOSQL
   REVOKE ALL PRIVILEGES ON DATABASE crypter FROM cryptuser;
   REVOKE ALL PRIVILEGES ON SCHEMA public FROM cryptuser;
   REVOKE CREATE ON SCHEMA public FROM PUBLIC;
   GRANT CONNECT ON DATABASE crypter TO cryptuser;
   ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cryptuser;
EOSQL