name: Reusable workflow to push and image of Crypter.API to a GitHub Container Registry

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true

env:
  registry: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      project_root: Crypter.API/
    environment: ${{ inputs.environment-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ env.API_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Crypter.API.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
