name: Release web application to GitHub Container Registry

on:
  release:
    types:
    - published

  workflow_dispatch:

env:
  registry: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      project_root: Crypter.Web/
      image_name: crypter_web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace tokens in configuration
        working-directory: ${{ env.project_root }}
        run: |
          sed -i 's|\\$\\{API_BASE_URL\\}|${{ vars.API_BASE_URL }}|g' wwwroot/appsettings.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ env.image_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Crypter.Web.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
