name: Push a development image of Crypter.Web to GitHub Container Registry

on:
  release:
    types:
      - published
  
  workflow_dispatch:

jobs:
  build-and-push-web-to-development:
    uses: crypter-file-transfer/crypter/.github/workflows/build-and-push-web.yml@f72a58c7d0f7486c74a551131ce57b6ebc4ba475
    with:
      environment-name: development
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
