name: Deploy web container to the production server

on:
  workflow_dispatch:

jobs:
  deploy-web-container:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop service
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          script: systemctl --user stop crypter.service
          script_stop: true

      - name: Push new systemctl service file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          source: crypter.service
          target: .config/systemd/user/

      - name: Reload systemctl daemon
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          script: systemctl --user daemon-reload

      - name: Push latest Docker Compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: crypter-web-container/

      - name: Pull latest images
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          script: docker compose --project-directory crypter-web-container --profile web pull
          script_stop: true

      - name: Migrate database
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          script: docker compose --project-directory crypter-web-container --profile dev run api /app/efbundle
          script_stop: true

      - name: Start service
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.APPSERVER_SSH_HOST }}
          port: ${{ secrets.APPSERVER_SSH_PORT }}
          username: ${{ secrets.APPSERVER_SSH_USER }}
          key: ${{ secrets.APPSERVER_SSH_PRIVATE_KEY }}
          script: systemctl --user start crypter.service
          script_stop: true
