name: .NET

on:
  push:
    branches: [ main, dev, stable ]
  pull_request:
    branches: [ main, dev, stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready

    - name: Configure PostgreSQL credential
      run: |
        sudo -u postgres psql --command="ALTER USER postgres PASSWORD 'password';" --command="\du"

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
