name: Build Crypter.Web image

on:
  pull_request:
    branches: [ main, stable ]

jobs:
  build-web:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Crypter.Web/Dockerfile
          push: false
