name: Unit test

on:
  pull_request:
    branches: [ main, stable ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Crypter.Test

      - name: Build
        run: dotnet build Crypter.Test --configuration Release --no-restore

      - name: Test
        run: dotnet test Crypter.Test --configuration Release --no-build --verbosity normal

  build-and-test-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - uses: pnpm/action-setup@v4
      with:
        version: 9
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Restore dependencies
      run: dotnet restore Crypter.Test.Web

    - name: Build
      run: dotnet build Crypter.Test.Web --configuration Release --no-restore

    - name: Test
      run: dotnet test Crypter.Test.Web --configuration Release --no-build --verbosity normal
