name: Unit test

on:
  pull_request:
    branches: [ main, stable ]

jobs:
  changes:
    uses: ./.github/workflows/detect-code-changes.yml

  build-and-test:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11.18.0

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore Crypter.Test

      - name: Build
        run: dotnet build Crypter.Test --configuration Release --no-restore

      - name: Test
        run: dotnet test Crypter.Test --configuration Release --no-build --verbosity normal

  build-and-test-web:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        version: 11.18.0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 10.0.x

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Restore dependencies
      run: dotnet restore Crypter.Test.Web

    - name: Build
      run: dotnet build Crypter.Test.Web --configuration Release --no-restore

    - name: Test
      run: dotnet test Crypter.Test.Web --configuration Release --no-build --verbosity normal
