name: Unit test

on:
  pull_request:
    branches: [ main, stable ]

jobs:
  changes:
    uses: ./.github/workflows/detect-code-changes.yml

  build-and-test:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v4
        with:
          version: 11.18.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore Crypter.Test

      - name: Build
        run: dotnet build Crypter.Test --configuration Release --no-restore

      - name: Test
        run: dotnet test Crypter.Test --configuration Release --no-build --verbosity normal

  build-and-test-web:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      
    - uses: pnpm/action-setup@v4
      with:
        version: 11.18.0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Restore dependencies
      run: dotnet restore Crypter.Test.Web

    - name: Build
      run: dotnet build Crypter.Test.Web --configuration Release --no-restore

    - name: Test
      run: dotnet test Crypter.Test.Web --configuration Release --no-build --verbosity normal
